# Generated by Django 2.0.4 on 2019-11-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WORD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(max_length=100)),
                ('times', models.IntegerField()),
                ('relate_1', models.CharField(max_length=100)),
                ('relate_2', models.CharField(max_length=100)),
                ('relate_3', models.CharField(max_length=100)),
                ('relate_4', models.CharField(max_length=100)),
                ('relate_5', models.CharField(max_length=100)),
                ('belong', models.CharField(max_length=100)),
                ('fans', models.CharField(max_length=100)),
            ],
        ),
    ]
